/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Database.KoneksiDatabase;
import Database.ResultSetTable;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Be
 */
public class FormKendaraan extends javax.swing.JFrame {

    ResultSet rs;
    KoneksiDatabase con;
    
    /**
     * Creates new form FormKendaraan
     */
    public FormKendaraan() {
        con =new KoneksiDatabase(new Database.Parameter().HOST_DB,new Database.Parameter().USERNAME_DB,new Database.Parameter().PASSWORD_DB);
        initComponents();
        loadTabel();
        
        inputIdKendaraan.setEditable(false);
        inputIdKendaraan.setBackground(Color.LIGHT_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelIdKendaraan = new javax.swing.JLabel();
        inputIdKendaraan = new javax.swing.JTextField();
        labelNoPolisi = new javax.swing.JLabel();
        inputNoPolisi = new javax.swing.JTextField();
        labelNamaKendaraan = new javax.swing.JLabel();
        inputNamaKendaraan = new javax.swing.JTextField();
        labelTahunKendaraan = new javax.swing.JLabel();
        inputTahunKendaraan = new javax.swing.JTextField();
        labelStatus = new javax.swing.JLabel();
        inputBiayaSewa = new javax.swing.JTextField();
        labelBiayaSewa = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnKembali = new javax.swing.JPanel();
        lblKembali = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKendaraan = new javax.swing.JTable();
        btnUbah = new javax.swing.JPanel();
        lblUbah = new javax.swing.JLabel();
        btnHapus = new javax.swing.JPanel();
        lblHapus = new javax.swing.JLabel();
        btnTambah = new javax.swing.JPanel();
        lblTambah = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JPanel();
        lblRefresh = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelCari = new javax.swing.JLabel();
        inputCari = new javax.swing.JTextField();
        comboStatus = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelIdKendaraan.setForeground(new java.awt.Color(253, 240, 213));
        labelIdKendaraan.setText("ID Kendaraan");
        getContentPane().add(labelIdKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, -1, -1));
        getContentPane().add(inputIdKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 186, -1));

        labelNoPolisi.setForeground(new java.awt.Color(253, 240, 213));
        labelNoPolisi.setText("No. Polisi");
        getContentPane().add(labelNoPolisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 71, -1, -1));
        getContentPane().add(inputNoPolisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 71, 186, -1));

        labelNamaKendaraan.setForeground(new java.awt.Color(253, 240, 213));
        labelNamaKendaraan.setText("Nama Kendaraan");
        getContentPane().add(labelNamaKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 42, -1, -1));
        getContentPane().add(inputNamaKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 42, 186, -1));

        labelTahunKendaraan.setForeground(new java.awt.Color(253, 240, 213));
        labelTahunKendaraan.setText("Tahun Kendaraan");
        getContentPane().add(labelTahunKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 101, -1, -1));
        getContentPane().add(inputTahunKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 101, 186, -1));

        labelStatus.setForeground(new java.awt.Color(253, 240, 213));
        labelStatus.setText("Status");
        getContentPane().add(labelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 161, -1, -1));
        getContentPane().add(inputBiayaSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 131, 186, -1));

        labelBiayaSewa.setForeground(new java.awt.Color(253, 240, 213));
        labelBiayaSewa.setText("Biaya Sewa");
        getContentPane().add(labelBiayaSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 131, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(74, 31, 61));
        jSeparator2.setForeground(new java.awt.Color(74, 31, 61));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 830, 10));

        btnKembali.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnKembali.setForeground(new java.awt.Color(253, 240, 213));
        btnKembali.setOpaque(false);
        btnKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKembaliMouseClicked(evt);
            }
        });
        btnKembali.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblKembali.setForeground(new java.awt.Color(253, 240, 213));
        lblKembali.setText("          Kembali");
        btnKembali.add(lblKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 107, 30));

        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 570, 107, 30));

        tblKendaraan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nama_kendaraan", "no_polisi", "tahun_kendaraan", "biaya_sewa", "status"
            }
        ));
        tblKendaraan.setFocusable(false);
        tblKendaraan.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblKendaraan.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tblKendaraan.setShowVerticalLines(false);
        tblKendaraan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKendaraanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKendaraan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 818, 275));

        btnUbah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnUbah.setOpaque(false);
        btnUbah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUbahMouseClicked(evt);
            }
        });
        btnUbah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUbah.setForeground(new java.awt.Color(253, 240, 213));
        lblUbah.setText("         Edit");
        btnUbah.add(lblUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 78, 30));

        getContentPane().add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 76, 30));

        btnHapus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnHapus.setOpaque(false);
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });
        btnHapus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHapus.setForeground(new java.awt.Color(253, 240, 213));
        lblHapus.setText("       Delete");
        btnHapus.add(lblHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 78, 30));

        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 76, 30));

        btnTambah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnTambah.setForeground(new java.awt.Color(253, 240, 213));
        btnTambah.setOpaque(false);
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });
        btnTambah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTambah.setForeground(new java.awt.Color(253, 240, 213));
        lblTambah.setText("       Create");
        btnTambah.add(lblTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 76, 30));

        btnRefresh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnRefresh.setOpaque(false);
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefreshMouseClicked(evt);
            }
        });
        btnRefresh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRefresh.setForeground(new java.awt.Color(253, 240, 213));
        lblRefresh.setText("     Refresh");
        btnRefresh.add(lblRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 78, 30));

        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 76, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconFormKendaraan.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 140, 110));

        labelCari.setForeground(new java.awt.Color(253, 240, 213));
        labelCari.setText("Search");
        getContentPane().add(labelCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        inputCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputCariKeyReleased(evt);
            }
        });
        getContentPane().add(inputCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 323, -1));

        comboStatus.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Keluar" }));
        getContentPane().add(comboStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 161, 100, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/gradientFormKendaraan.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUbahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahMouseClicked
        try{
            if(!inputIdKendaraan.getText().isEmpty() && !inputNamaKendaraan.getText().isEmpty() && !inputTahunKendaraan.getText().isEmpty() && !inputNoPolisi.getText().isEmpty() && !inputBiayaSewa.getText().isEmpty()){
                String kolom[] = {"id","nama_kendaraan","tahun_kendaraan","no_polisi","biaya_sewa","status"};
                String isi[] = {inputIdKendaraan.getText(),inputNamaKendaraan.getText(),inputTahunKendaraan.getText(),inputNoPolisi.getText(),inputBiayaSewa.getText(),comboStatus.getSelectedItem().toString()};
                con.queryUpdate("kendaraan", kolom, isi, "id='"+String.valueOf(tblKendaraan.getValueAt(tblKendaraan.getSelectedRow(),0))+"'");
                JOptionPane.showMessageDialog(this, "Data Berhasil Diedit");
            } else {
                JOptionPane.showMessageDialog(this, "Data isian ada yang kosong");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error edit data");
        }
        loadTabel();
        clear();
    }//GEN-LAST:event_btnUbahMouseClicked

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        try{
            String id=String.valueOf(tblKendaraan.getValueAt(tblKendaraan.getSelectedRow(), 0));
            if(JOptionPane.showConfirmDialog(this, "Yakin menghapus data?", "Peringatan", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
                con.queryDelete("kendaraan","id="+id);
            } else {
                return;
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Pilih id terlebih dahulu");
        }
        loadTabel();
        clear();
    }//GEN-LAST:event_btnHapusMouseClicked

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        create();
    }//GEN-LAST:event_btnTambahMouseClicked

    private void btnRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseClicked
        loadTabel();
    }//GEN-LAST:event_btnRefreshMouseClicked

    private void btnKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKembaliMouseClicked
        this.dispose();
        System.out.println("Panggil Form Sewa");
        FormSewa callForm = new FormSewa();
        callForm.setLocationRelativeTo(null);
        callForm.setVisible(true);
    }//GEN-LAST:event_btnKembaliMouseClicked

    private void inputCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCariKeyReleased
        try {
            rs=con.querySelectAll("kendaraan", "nama_kendaraan LIKE '%"+inputCari.getText()+"%' OR status LIKE '%"+inputCari.getText()+"%'");
            tblKendaraan.setModel(new Database.ResultSetTable(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Pencarian Error");
        }
    }//GEN-LAST:event_inputCariKeyReleased

    private void tblKendaraanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKendaraanMouseClicked
        inputIdKendaraan.setText((String.valueOf(tblKendaraan.getValueAt(tblKendaraan.getSelectedRow(), 0))));
        inputNamaKendaraan.setText((String.valueOf(tblKendaraan.getValueAt(tblKendaraan.getSelectedRow(), 1))));
        inputNoPolisi.setText((String.valueOf(tblKendaraan.getValueAt(tblKendaraan.getSelectedRow(), 2))));
        inputTahunKendaraan.setText((String.valueOf(tblKendaraan.getValueAt(tblKendaraan.getSelectedRow(), 3))));
        inputBiayaSewa.setText((String.valueOf(tblKendaraan.getValueAt(tblKendaraan.getSelectedRow(), 4))));
    }//GEN-LAST:event_tblKendaraanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKendaraan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnHapus;
    private javax.swing.JPanel btnKembali;
    private javax.swing.JPanel btnRefresh;
    private javax.swing.JPanel btnTambah;
    private javax.swing.JPanel btnUbah;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JTextField inputBiayaSewa;
    private javax.swing.JTextField inputCari;
    private javax.swing.JTextField inputIdKendaraan;
    private javax.swing.JTextField inputNamaKendaraan;
    private javax.swing.JTextField inputNoPolisi;
    private javax.swing.JTextField inputTahunKendaraan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelBiayaSewa;
    private javax.swing.JLabel labelCari;
    private javax.swing.JLabel labelIdKendaraan;
    private javax.swing.JLabel labelNamaKendaraan;
    private javax.swing.JLabel labelNoPolisi;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelTahunKendaraan;
    private javax.swing.JLabel lblHapus;
    private javax.swing.JLabel lblKembali;
    private javax.swing.JLabel lblRefresh;
    private javax.swing.JLabel lblTambah;
    private javax.swing.JLabel lblUbah;
    private javax.swing.JTable tblKendaraan;
    // End of variables declaration//GEN-END:variables

    private void loadTabel() {
        String namaKolom[] = {"id","nama_kendaraan","no_polisi","tahun_kendaraan","biaya_sewa","status"};
        rs=con.querySelect(namaKolom,"kendaraan");
        tblKendaraan.setModel(new ResultSetTable(rs));
    }

    private void clear() {
        inputIdKendaraan.setText("");
        inputNamaKendaraan.setText("");
        inputNoPolisi.setText("");
        inputTahunKendaraan.setText("");
        inputBiayaSewa.setText("");
    }
    
    private void create() {
        try {
            if( !inputNamaKendaraan.getText().isEmpty() && !inputNoPolisi.getText().isEmpty() && !inputTahunKendaraan.getText().isEmpty() && !inputBiayaSewa.getText().isEmpty()){
                String kolom[] = {"nama_kendaraan","no_polisi","tahun_kendaraan","biaya_sewa","status"};
                String isi[] = {inputNamaKendaraan.getText(),inputNoPolisi.getText(),inputTahunKendaraan.getText(),inputBiayaSewa.getText(),comboStatus.getSelectedItem().toString()};
                
                System.out.println( con.queryInsert("kendaraan",kolom,isi));
               
                JOptionPane.showMessageDialog(this, "Kendaraan Berhasil Ditambahkan");
            }else{
                JOptionPane.showMessageDialog(this, "Data Kendaraan Masih ada yang kosong");
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error input data");
             System.out.println("salah");
        }
        loadTabel();
        clear();
    }
}
