/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Database.KoneksiDatabase;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Be
 */
public class FormSewa extends javax.swing.JFrame {

    ResultSet rs;
    KoneksiDatabase con;
    
    /**
     * Creates new form FormSewa
     */
    public FormSewa() {
        con = new KoneksiDatabase(new Database.Parameter().HOST_DB, new Database.Parameter().USERNAME_DB, new Database.Parameter().PASSWORD_DB);
        initComponents();
        loadPelanggan();
        inputNoSewa.setEditable(false);
        inputNoSewa.setBackground(Color.LIGHT_GRAY);
        inputNamaPelanggan.setEditable(false);
        inputNamaPelanggan.setBackground(Color.LIGHT_GRAY);
        inputAlamat.setEditable(false);
        inputAlamat.setBackground(Color.LIGHT_GRAY);
        inputNoIdentitas.setEditable(false);
        inputNoIdentitas.setBackground(Color.LIGHT_GRAY);
        inputNoTelepon.setEditable(false);
        inputNoTelepon.setBackground(Color.LIGHT_GRAY);
        
        loadMotor();
        inputNamaKendaraan.setEditable(false);
        inputNamaKendaraan.setBackground(Color.LIGHT_GRAY);
        inputTahunKendaraan.setEditable(false);
        inputTahunKendaraan.setBackground(Color.LIGHT_GRAY);
        inputNoPolisi.setEditable(false);
        inputNoPolisi.setBackground(Color.LIGHT_GRAY);
        inputBiayaSewa.setEditable(false);
        inputBiayaSewa.setBackground(Color.LIGHT_GRAY);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSimpan = new javax.swing.JPanel();
        lblSimpan = new javax.swing.JLabel();
        btnFormUser = new javax.swing.JPanel();
        lblFormUser = new javax.swing.JLabel();
        btnFormKendaraan = new javax.swing.JPanel();
        lblFormKendaraan = new javax.swing.JLabel();
        btnFormPelanggan = new javax.swing.JPanel();
        lblFormPelanggan = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JPanel();
        lblKeluar = new javax.swing.JLabel();
        labelNoSewa = new javax.swing.JLabel();
        labelIdPelanggan = new javax.swing.JLabel();
        labelNamaPelanggan = new javax.swing.JLabel();
        labelAlamat = new javax.swing.JLabel();
        labelNoTelp = new javax.swing.JLabel();
        labelNoIdentitas = new javax.swing.JLabel();
        labelIdKendaraan = new javax.swing.JLabel();
        labelNamaKendaraan = new javax.swing.JLabel();
        labelNoPolisi = new javax.swing.JLabel();
        inputNoSewa = new javax.swing.JTextField();
        inputIdPelanggan = new javax.swing.JComboBox<>();
        inputAlamat = new javax.swing.JTextField();
        inputNamaPelanggan = new javax.swing.JTextField();
        inputNoTelepon = new javax.swing.JTextField();
        inputNoIdentitas = new javax.swing.JTextField();
        inputIdKendaraan = new javax.swing.JComboBox<>();
        inputNamaKendaraan = new javax.swing.JTextField();
        inputNoPolisi = new javax.swing.JTextField();
        labelTahunKendaraan = new javax.swing.JLabel();
        labelBiaya = new javax.swing.JLabel();
        inputTahunKendaraan = new javax.swing.JTextField();
        inputBiayaSewa = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSimpan.setBackground(new java.awt.Color(186, 79, 84));
        btnSimpan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnSimpan.setOpaque(false);
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });
        btnSimpan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSimpan.setForeground(new java.awt.Color(253, 240, 213));
        lblSimpan.setText("     Simpan Transaksi");
        btnSimpan.add(lblSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 130, 32));

        btnFormUser.setBackground(new java.awt.Color(186, 79, 84));
        btnFormUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnFormUser.setOpaque(false);
        btnFormUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFormUserMouseClicked(evt);
            }
        });
        btnFormUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFormUser.setForeground(new java.awt.Color(253, 240, 213));
        lblFormUser.setText("            Form User");
        btnFormUser.add(lblFormUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        getContentPane().add(btnFormUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 130, 32));

        btnFormKendaraan.setBackground(new java.awt.Color(186, 79, 84));
        btnFormKendaraan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnFormKendaraan.setOpaque(false);
        btnFormKendaraan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFormKendaraanMouseClicked(evt);
            }
        });
        btnFormKendaraan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFormKendaraan.setForeground(new java.awt.Color(253, 240, 213));
        lblFormKendaraan.setText("      Form Kendaraan");
        btnFormKendaraan.add(lblFormKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        getContentPane().add(btnFormKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 130, 32));

        btnFormPelanggan.setBackground(new java.awt.Color(186, 79, 84));
        btnFormPelanggan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnFormPelanggan.setOpaque(false);
        btnFormPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFormPelangganMouseClicked(evt);
            }
        });
        btnFormPelanggan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFormPelanggan.setForeground(new java.awt.Color(253, 240, 213));
        lblFormPelanggan.setText("     Form Pelanggan");
        btnFormPelanggan.add(lblFormPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        getContentPane().add(btnFormPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 119, 32));

        btnKeluar.setBackground(new java.awt.Color(186, 79, 84));
        btnKeluar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnKeluar.setOpaque(false);
        btnKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKeluarMouseClicked(evt);
            }
        });
        btnKeluar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblKeluar.setForeground(new java.awt.Color(253, 240, 213));
        lblKeluar.setText("     Keluar");
        btnKeluar.add(lblKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 67, 32));

        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 67, 32));

        labelNoSewa.setBackground(new java.awt.Color(253, 240, 213));
        labelNoSewa.setForeground(new java.awt.Color(253, 240, 213));
        labelNoSewa.setText("No. Sewa");
        getContentPane().add(labelNoSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 23, -1, -1));

        labelIdPelanggan.setForeground(new java.awt.Color(253, 240, 213));
        labelIdPelanggan.setText("ID Pelanggan");
        getContentPane().add(labelIdPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 61, -1, -1));

        labelNamaPelanggan.setForeground(new java.awt.Color(253, 240, 213));
        labelNamaPelanggan.setText("Nama Pelanggan");
        getContentPane().add(labelNamaPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 95, -1, -1));

        labelAlamat.setForeground(new java.awt.Color(253, 240, 213));
        labelAlamat.setText("Alamat");
        getContentPane().add(labelAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 129, -1, -1));

        labelNoTelp.setForeground(new java.awt.Color(253, 240, 213));
        labelNoTelp.setText("No. Telp");
        getContentPane().add(labelNoTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 193, -1, -1));

        labelNoIdentitas.setForeground(new java.awt.Color(253, 240, 213));
        labelNoIdentitas.setText("No. Identitas");
        getContentPane().add(labelNoIdentitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 227, -1, -1));

        labelIdKendaraan.setForeground(new java.awt.Color(253, 240, 213));
        labelIdKendaraan.setText("ID Kendaraan");
        getContentPane().add(labelIdKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        labelNamaKendaraan.setForeground(new java.awt.Color(253, 240, 213));
        labelNamaKendaraan.setText("Nama Kendaraan");
        getContentPane().add(labelNamaKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        labelNoPolisi.setForeground(new java.awt.Color(253, 240, 213));
        labelNoPolisi.setText("No Polisi");
        getContentPane().add(labelNoPolisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));
        getContentPane().add(inputNoSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 23, 195, -1));

        inputIdPelanggan.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        inputIdPelanggan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih ID" }));
        inputIdPelanggan.setToolTipText("");
        inputIdPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdPelangganActionPerformed(evt);
            }
        });
        getContentPane().add(inputIdPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 61, 195, -1));

        inputAlamat.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(inputAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 129, 195, 50));
        getContentPane().add(inputNamaPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 95, 195, -1));
        getContentPane().add(inputNoTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 193, 195, -1));
        getContentPane().add(inputNoIdentitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 227, 195, -1));

        inputIdKendaraan.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        inputIdKendaraan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kendaraan" }));
        inputIdKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdKendaraanActionPerformed(evt);
            }
        });
        getContentPane().add(inputIdKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 195, -1));
        getContentPane().add(inputNamaKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 195, -1));
        getContentPane().add(inputNoPolisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 195, -1));

        labelTahunKendaraan.setForeground(new java.awt.Color(253, 240, 213));
        labelTahunKendaraan.setText("Tahun Kendaraan");
        getContentPane().add(labelTahunKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        labelBiaya.setForeground(new java.awt.Color(253, 240, 213));
        labelBiaya.setText("Biaya Sewa perhari");
        getContentPane().add(labelBiaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));
        getContentPane().add(inputTahunKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 120, -1));
        getContentPane().add(inputBiayaSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 120, -1));

        jSeparator1.setBackground(new java.awt.Color(74, 31, 61));
        jSeparator1.setForeground(new java.awt.Color(74, 31, 61));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 640, 10));

        jSeparator2.setBackground(new java.awt.Color(74, 31, 61));
        jSeparator2.setForeground(new java.awt.Color(74, 31, 61));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 640, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconSewa.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 110, 110));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/gradientFormSewa.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputIdPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdPelangganActionPerformed
        String st = (String) inputIdPelanggan.getSelectedItem();
        ResultSet rst = con.querySelectAll("pelanggan", "id='" + st + "'");
        try {
            while (rst.next()){
                
                this.inputNamaPelanggan.setText(rst.getString("nama_pelanggan"));
                this.inputAlamat.setText(rst.getString("alamat"));
                this.inputNoTelepon.setText(rst.getString("no_telp"));
                this.inputNoIdentitas.setText(rst.getString("no_identitas"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormSewa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_inputIdPelangganActionPerformed

    private void inputIdKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdKendaraanActionPerformed
        String st = (String) inputIdKendaraan.getSelectedItem();
        ResultSet rst = con.querySelectAll("kendaraan", "id='" + st + "'");
        try {
            while (rst.next()){
                
                this.inputNamaKendaraan.setText(rst.getString("nama_kendaraan"));
                this.inputNoPolisi.setText(rst.getString("no_polisi"));
                this.inputTahunKendaraan.setText(rst.getString("tahun_kendaraan"));
                this.inputBiayaSewa.setText(rst.getString("biaya_sewa"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormSewa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_inputIdKendaraanActionPerformed

    private void btnKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnKeluarMouseClicked

    private void btnFormKendaraanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFormKendaraanMouseClicked
        dispose();
        FormKendaraan fk = new FormKendaraan();
        fk.setVisible(true);
    }//GEN-LAST:event_btnFormKendaraanMouseClicked

    private void btnFormPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFormPelangganMouseClicked
        dispose();
        FormPelanggan fp = new FormPelanggan();
        fp.setVisible(true);
    }//GEN-LAST:event_btnFormPelangganMouseClicked

    private void btnFormUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFormUserMouseClicked
        dispose();
        FormUser fu = new FormUser();
        fu.setVisible(true);
    }//GEN-LAST:event_btnFormUserMouseClicked

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        if(inputNamaPelanggan.getText().isEmpty() || inputNamaKendaraan.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Data isian ada yang kosong");
        } else {
            String nama = inputNamaPelanggan.getText();
            String alamat = inputAlamat.getText();
            String tlp = inputNoTelepon.getText();
            String iden = inputNoIdentitas.getText();
            
            String namak = inputNamaKendaraan.getText();
            String nopol = inputNoPolisi.getText();
            String tahun = inputTahunKendaraan.getText();
            String biaya = inputBiayaSewa.getText();
            
            dispose();
            FormTransaksi ft = new FormTransaksi(nama,alamat,tlp,iden,namak,nopol,tahun,biaya);
            ft.setVisible(true);
        }
    }//GEN-LAST:event_btnSimpanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSewa().setVisible(true);
            }
        });
    }
    
    public void admin(){
        btnFormUser.setVisible(true);
        btnFormKendaraan.setVisible(true);
        btnFormPelanggan.setVisible(true);
    }
    
    public void staff(){
        btnFormUser.setVisible(false);
        lblFormUser.setVisible(false);
        btnFormKendaraan.setVisible(true);
        btnFormPelanggan.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel btnFormKendaraan;
    private javax.swing.JPanel btnFormPelanggan;
    private javax.swing.JPanel btnFormUser;
    private javax.swing.JPanel btnKeluar;
    private javax.swing.JPanel btnSimpan;
    private javax.swing.JTextField inputAlamat;
    private javax.swing.JTextField inputBiayaSewa;
    private javax.swing.JComboBox<String> inputIdKendaraan;
    private javax.swing.JComboBox<String> inputIdPelanggan;
    private javax.swing.JTextField inputNamaKendaraan;
    private javax.swing.JTextField inputNamaPelanggan;
    private javax.swing.JTextField inputNoIdentitas;
    private javax.swing.JTextField inputNoPolisi;
    private javax.swing.JTextField inputNoSewa;
    private javax.swing.JTextField inputNoTelepon;
    private javax.swing.JTextField inputTahunKendaraan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelBiaya;
    private javax.swing.JLabel labelIdKendaraan;
    private javax.swing.JLabel labelIdPelanggan;
    private javax.swing.JLabel labelNamaKendaraan;
    private javax.swing.JLabel labelNamaPelanggan;
    private javax.swing.JLabel labelNoIdentitas;
    private javax.swing.JLabel labelNoPolisi;
    private javax.swing.JLabel labelNoSewa;
    private javax.swing.JLabel labelNoTelp;
    private javax.swing.JLabel labelTahunKendaraan;
    private javax.swing.JLabel lblFormKendaraan;
    private javax.swing.JLabel lblFormPelanggan;
    private javax.swing.JLabel lblFormUser;
    private javax.swing.JLabel lblKeluar;
    private javax.swing.JLabel lblSimpan;
    // End of variables declaration//GEN-END:variables
    
    private void loadPelanggan(){
        
        rs = con.querySelectAll("pelanggan");
        try{
            while(rs.next()){
                inputIdPelanggan.addItem(rs.getString("id"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormSewa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadMotor(){
        
        rs = con.querySelectAll("kendaraan");
        try{
            while(rs.next()){
                inputIdKendaraan.addItem(rs.getString("id"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormSewa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
