/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Database.KoneksiDatabase;
import Database.ResultSetTable;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Be
 */
public class FormUser extends javax.swing.JFrame {
    
    ResultSet rs;
    KoneksiDatabase con;
    
    /**
     * Creates new form FormUser
     */
    public FormUser() {
        con =new KoneksiDatabase(new Database.Parameter().HOST_DB,new Database.Parameter().USERNAME_DB,new Database.Parameter().PASSWORD_DB);
        initComponents();
        loadTabel();
        
        inputIdUser.setEditable(false);
        inputIdUser.setBackground(Color.LIGHT_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelIdUser = new javax.swing.JLabel();
        inputIdUser = new javax.swing.JTextField();
        labelNama = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        inputUsername = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        labelType = new javax.swing.JLabel();
        inputType = new javax.swing.JComboBox<>();
        inputCari = new javax.swing.JTextField();
        labelCari = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JPanel();
        lblRefresh = new javax.swing.JLabel();
        ICON = new javax.swing.JLabel();
        btnHapus = new javax.swing.JPanel();
        lblHapus = new javax.swing.JLabel();
        btnUbah = new javax.swing.JPanel();
        lblUbah = new javax.swing.JLabel();
        btnTambah = new javax.swing.JPanel();
        lblTambah = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        btnKembali = new javax.swing.JPanel();
        lblKembali = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelIdUser.setForeground(new java.awt.Color(253, 240, 213));
        labelIdUser.setText("ID User");
        getContentPane().add(labelIdUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 27, -1, -1));
        getContentPane().add(inputIdUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 23, 180, -1));

        labelNama.setForeground(new java.awt.Color(253, 240, 213));
        labelNama.setText("Nama");
        getContentPane().add(labelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 63, -1, -1));
        getContentPane().add(inputNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 59, 180, -1));
        getContentPane().add(inputUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 95, 180, -1));

        labelPassword.setForeground(new java.awt.Color(253, 240, 213));
        labelPassword.setText("Password");
        getContentPane().add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 134, -1, -1));
        getContentPane().add(inputPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 131, 180, -1));

        labelType.setForeground(new java.awt.Color(253, 240, 213));
        labelType.setText("Type");
        getContentPane().add(labelType, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        inputType.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        inputType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Staff" }));
        getContentPane().add(inputType, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 167, 180, -1));

        inputCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputCariKeyReleased(evt);
            }
        });
        getContentPane().add(inputCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 245, 323, -1));

        labelCari.setForeground(new java.awt.Color(253, 240, 213));
        labelCari.setText("Search");
        getContentPane().add(labelCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 245, -1, -1));

        labelUsername.setForeground(new java.awt.Color(253, 240, 213));
        labelUsername.setText("Username");
        getContentPane().add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 99, -1, -1));

        btnRefresh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnRefresh.setOpaque(false);
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefreshMouseClicked(evt);
            }
        });
        btnRefresh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRefresh.setForeground(new java.awt.Color(253, 240, 213));
        lblRefresh.setText("     Refresh");
        btnRefresh.add(lblRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 78, 30));

        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 207, 76, 30));

        ICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconUser.png"))); // NOI18N
        getContentPane().add(ICON, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        btnHapus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnHapus.setOpaque(false);
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });
        btnHapus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHapus.setForeground(new java.awt.Color(253, 240, 213));
        lblHapus.setText("       Delete");
        btnHapus.add(lblHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 78, 30));

        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 207, 76, 30));

        btnUbah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnUbah.setOpaque(false);
        btnUbah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUbahMouseClicked(evt);
            }
        });
        btnUbah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUbah.setForeground(new java.awt.Color(253, 240, 213));
        lblUbah.setText("         Edit");
        btnUbah.add(lblUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 78, 30));

        getContentPane().add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 207, 76, 30));

        btnTambah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnTambah.setForeground(new java.awt.Color(253, 240, 213));
        btnTambah.setOpaque(false);
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });
        btnTambah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTambah.setForeground(new java.awt.Color(253, 240, 213));
        lblTambah.setText("       Create");
        btnTambah.add(lblTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 207, 76, 30));

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Username", "Type"
            }
        ));
        tblUser.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblUser.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblUser);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 271, 656, 163));

        jSeparator2.setBackground(new java.awt.Color(74, 31, 61));
        jSeparator2.setForeground(new java.awt.Color(74, 31, 61));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 445, 665, 10));

        btnKembali.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnKembali.setForeground(new java.awt.Color(253, 240, 213));
        btnKembali.setOpaque(false);
        btnKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKembaliMouseClicked(evt);
            }
        });
        btnKembali.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblKembali.setForeground(new java.awt.Color(253, 240, 213));
        lblKembali.setText("          Kembali");
        btnKembali.add(lblKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 107, 30));

        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 107, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/gradientFormUser.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 665, 502));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserMouseClicked
        inputIdUser.setText(String.valueOf(tblUser.getValueAt(tblUser.getSelectedRow(), 0)));
        inputNama.setText(String.valueOf(tblUser.getValueAt(tblUser.getSelectedRow(), 1)));
        inputUsername.setText(String.valueOf(tblUser.getValueAt(tblUser.getSelectedRow(), 2)));
        inputType.setSelectedItem(String.valueOf(tblUser.getValueAt(tblUser.getSelectedRow(), 3)));
    }//GEN-LAST:event_tblUserMouseClicked

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        create();   
    }//GEN-LAST:event_btnTambahMouseClicked

    private void btnUbahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahMouseClicked
        try{
            if(!inputIdUser.getText().isEmpty() && !inputNama.getText().isEmpty() && !inputPassword.getText().isEmpty()){
            String kolom[] = {"id","nama","username","password","type"};
            String isi[] = {inputIdUser.getText(),inputNama.getText(),inputUsername.getText(),inputPassword.getText(),inputType.getSelectedItem().toString()};
            
            con.queryUpdate("user", kolom, isi, "id='"+String.valueOf(tblUser.getValueAt(tblUser.getSelectedRow(),0))+"'");
            JOptionPane.showMessageDialog(this, "Data Berhasil Diedit");
            } else {
                JOptionPane.showMessageDialog(this, "Data isina ada yang kosong");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error edit data");
        }
        loadTabel();
        clear();    
    }//GEN-LAST:event_btnUbahMouseClicked

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        try{
            String id=String.valueOf(tblUser.getValueAt(tblUser.getSelectedRow(), 0));
            if(JOptionPane.showConfirmDialog(this, "Yakin menghapus data?", "Peringatan", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
                con.queryDelete("user","id="+id);
            } else {
                return;
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Pilih id terlebih dahulu");
        }
        loadTabel();
        clear();
    }//GEN-LAST:event_btnHapusMouseClicked

    private void btnRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseClicked
        loadTabel();
    }//GEN-LAST:event_btnRefreshMouseClicked

    private void inputCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCariKeyReleased
        try {
                String kolom[] = {"id","nama","username","type"};
                rs=con.querySelect(kolom ,"user", "nama LIKE '%"+inputCari.getText()+"%' OR type LIKE '%"+inputCari.getText()+"%'");
                tblUser.setModel(new Database.ResultSetTable(rs));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Pencarian Error");
            }
    }//GEN-LAST:event_inputCariKeyReleased

    private void btnKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKembaliMouseClicked
        this.dispose();
        System.out.println("Panggil Form Sewa");
        FormSewa callForm = new FormSewa();
        callForm.setLocationRelativeTo(null);
        callForm.setVisible(true);
    }//GEN-LAST:event_btnKembaliMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ICON;
    private javax.swing.JPanel btnHapus;
    private javax.swing.JPanel btnKembali;
    private javax.swing.JPanel btnRefresh;
    private javax.swing.JPanel btnTambah;
    private javax.swing.JPanel btnUbah;
    private javax.swing.JTextField inputCari;
    private javax.swing.JTextField inputIdUser;
    private javax.swing.JTextField inputNama;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JComboBox<String> inputType;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelCari;
    private javax.swing.JLabel labelIdUser;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelType;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel lblHapus;
    private javax.swing.JLabel lblKembali;
    private javax.swing.JLabel lblRefresh;
    private javax.swing.JLabel lblTambah;
    private javax.swing.JLabel lblUbah;
    private javax.swing.JTable tblUser;
    // End of variables declaration//GEN-END:variables

    private void loadTabel(){
        String namaKolom[] = {"id","nama","username","type"};
        rs=con.querySelect(namaKolom, "user");
        tblUser.setModel(new ResultSetTable(rs));
        }
    
    private void clear(){
        inputIdUser.setText("");
        inputNama.setText("");
        inputPassword.setText("");
        inputType.setSelectedItem("Type");
    }
    
    private void create(){
        try{
            if(!inputNama.getText().isEmpty() && !inputUsername.getText().isEmpty() && !inputPassword.getText().isEmpty()){
                String kolom[] = {"nama","username","password","type"};
                String isi[] = {inputNama.getText(),inputUsername.getText(),inputPassword.getText(),inputType.getSelectedItem().toString()};
                
                System.out.println( con.queryInsert("user",kolom,isi));
                
                JOptionPane.showMessageDialog(this, "User Berhasil ditambahkan");
            } else {
                JOptionPane.showMessageDialog(this, "Data User Masih ada yang Kosong");
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error input data");
            System.out.println("salah");
        }
        loadTabel();
        clear();
    }
}

