/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Database.KoneksiDatabase;
import Database.ResultSetTable;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Be
 */
public class FormTransaksi extends javax.swing.JFrame {

    ResultSet rs;
    KoneksiDatabase con;
    static String nosewa;
    static String nama;
    static String alamat;
    static String tlp;
    static String iden;
    static String namak;
    static String nopol;
    static String tahun;
    static String biaya;
    String status1;
    
    /**
     * Creates new form FormTransaksi
     */
    public FormTransaksi(String nama, String alamat, String tlp, String iden, String namak, String nopol, String tahun, String biaya) {
        con = new KoneksiDatabase(new Database.Parameter().HOST_DB, new Database.Parameter().USERNAME_DB, new Database.Parameter().PASSWORD_DB);
        
        initComponents();
        lblNoSewa.setText(nosewa);
        inputNoSewa.setEditable(false);
        inputNoSewa.setBackground(Color.LIGHT_GRAY);
        lblNama.setText(nama);
        inputNamaPelanggan.setEditable(false);
        inputNamaPelanggan.setBackground(Color.LIGHT_GRAY);
        lblAlamat.setText(alamat);
        inputAlamat.setEditable(false);
        inputAlamat.setBackground(Color.LIGHT_GRAY);
        lblTlp.setText(tlp);
        inputNoTelp.setEditable(false);
        inputNoTelp.setBackground(Color.LIGHT_GRAY);
        lblIden.setText(iden);
        inputNoIdentitas.setEditable(false);
        inputNoIdentitas.setBackground(Color.LIGHT_GRAY);
    
        lblNamak.setText(namak);
        inputNamaKendaraan.setEditable(false);
        inputNamaKendaraan.setBackground(Color.LIGHT_GRAY);
        lblNopol.setText(nopol);
        inputNoPolisi.setEditable(false);
        inputNoPolisi.setBackground(Color.LIGHT_GRAY);
        lblTahun.setText(tahun);
        inputTahunKendaraan.setEditable(false);
        inputTahunKendaraan.setBackground(Color.LIGHT_GRAY);
        lblHarga.setText(biaya);
        inputBiayaSewa.setEditable(false);
        inputBiayaSewa.setBackground(Color.LIGHT_GRAY);
        inputHari.setEditable(false);
        inputBiayaTotal.setEditable(false);
        loadTabel();
    }

    private FormTransaksi(String nama, String alamat, String iden, String namak, String nopol, String tahun, String biaya) {
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNoSewa = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblAlamat = new javax.swing.JLabel();
        lblTlp = new javax.swing.JLabel();
        lblIden = new javax.swing.JLabel();
        lblNamak = new javax.swing.JLabel();
        lblNopol = new javax.swing.JLabel();
        lblTahun = new javax.swing.JLabel();
        labelNoSewa = new javax.swing.JLabel();
        labelNamaPelanggan = new javax.swing.JLabel();
        labelAlamat = new javax.swing.JLabel();
        labelNoTelp = new javax.swing.JLabel();
        labelNoIdentitas = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelNamaKendaraan = new javax.swing.JLabel();
        labelNoPolisi = new javax.swing.JLabel();
        labelTahunKendaraan = new javax.swing.JLabel();
        labelLamaSewa = new javax.swing.JLabel();
        labelBiayaSewa = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        inputTanggalMulai = new com.toedter.calendar.JDateChooser();
        inputTanggalAkhir = new com.toedter.calendar.JDateChooser();
        btnSubmit = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        inputNoSewa = new javax.swing.JTextField();
        inputNamaPelanggan = new javax.swing.JTextField();
        inputAlamat = new javax.swing.JTextArea();
        inputNoTelp = new javax.swing.JTextField();
        inputNoIdentitas = new javax.swing.JTextField();
        inputNamaKendaraan = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        inputNoPolisi = new javax.swing.JTextField();
        inputTahunKendaraan = new javax.swing.JTextField();
        inputHari = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        labelDariTanggal = new javax.swing.JLabel();
        labelSampai = new javax.swing.JLabel();
        labelKali = new javax.swing.JLabel();
        labelRpSewa = new javax.swing.JLabel();
        inputBiayaSewa = new javax.swing.JTextField();
        labelRpBiaya = new javax.swing.JLabel();
        inputBiayaTotal = new javax.swing.JTextField();
        textTanggal = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_transaksi = new javax.swing.JTable();
        btnKembali = new javax.swing.JPanel();
        lblKembali = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNoSewa.setText("NoSewa");
        getContentPane().add(lblNoSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        lblNama.setText("Nama Pelanggan");
        getContentPane().add(lblNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 45, -1, -1));

        lblAlamat.setText("Alamat");
        getContentPane().add(lblAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        lblTlp.setText("Nomor Telpon");
        getContentPane().add(lblTlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 173, -1, -1));

        lblIden.setText("Nomor Identitas");
        getContentPane().add(lblIden, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 209, -1, -1));

        lblNamak.setText("Nama Kendaraan");
        getContentPane().add(lblNamak, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 273, -1, -1));

        lblNopol.setText("Nomor Polisi");
        getContentPane().add(lblNopol, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 309, -1, -1));

        lblTahun.setText("Tahun Kendaraan");
        getContentPane().add(lblTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 345, -1, -1));

        labelNoSewa.setBackground(new java.awt.Color(253, 240, 213));
        labelNoSewa.setForeground(new java.awt.Color(253, 240, 213));
        labelNoSewa.setText("No. Sewa");
        getContentPane().add(labelNoSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, -1, -1));

        labelNamaPelanggan.setForeground(new java.awt.Color(253, 240, 213));
        labelNamaPelanggan.setText("Nama Pelanggan");
        getContentPane().add(labelNamaPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 46, -1, -1));

        labelAlamat.setForeground(new java.awt.Color(253, 240, 213));
        labelAlamat.setText("Alamat");
        getContentPane().add(labelAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 78, -1, -1));

        labelNoTelp.setForeground(new java.awt.Color(253, 240, 213));
        labelNoTelp.setText("No. Telp");
        getContentPane().add(labelNoTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 173, -1, -1));

        labelNoIdentitas.setForeground(new java.awt.Color(253, 240, 213));
        labelNoIdentitas.setText("No. Identitas");
        getContentPane().add(labelNoIdentitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 209, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(74, 31, 61));
        jSeparator1.setForeground(new java.awt.Color(74, 31, 61));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 247, 484, 10));

        labelNamaKendaraan.setForeground(new java.awt.Color(253, 240, 213));
        labelNamaKendaraan.setText("Nama Kendaraan");
        getContentPane().add(labelNamaKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 273, -1, -1));

        labelNoPolisi.setForeground(new java.awt.Color(253, 240, 213));
        labelNoPolisi.setText("No. Polisi");
        getContentPane().add(labelNoPolisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 309, -1, -1));

        labelTahunKendaraan.setForeground(new java.awt.Color(253, 240, 213));
        labelTahunKendaraan.setText("Tahun Kendaraan");
        getContentPane().add(labelTahunKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 345, -1, -1));

        labelLamaSewa.setForeground(new java.awt.Color(253, 240, 213));
        labelLamaSewa.setText("Lama Sewa");
        getContentPane().add(labelLamaSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 409, -1, -1));

        labelBiayaSewa.setForeground(new java.awt.Color(253, 240, 213));
        labelBiayaSewa.setText("Biaya Sewa");
        getContentPane().add(labelBiayaSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 517, -1, -1));

        lblHarga.setText("Harga per hari");
        getContentPane().add(lblHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 517, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(74, 31, 61));
        jSeparator3.setForeground(new java.awt.Color(74, 31, 61));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 620, 1100, 10));

        inputTanggalMulai.setDateFormatString("dd MMMM, yyyy");
        getContentPane().add(inputTanggalMulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 271, -1));

        inputTanggalAkhir.setDateFormatString("dd MMMM, yyyy");
        getContentPane().add(inputTanggalAkhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 271, -1));

        btnSubmit.setText("Submit");
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitMouseClicked(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, 107, -1));

        btnRefresh.setText("Refresh");
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefreshMouseClicked(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 580, 107, -1));
        getContentPane().add(inputNoSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 6, 354, -1));
        getContentPane().add(inputNamaPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 42, 354, -1));

        inputAlamat.setColumns(20);
        inputAlamat.setRows(4);
        getContentPane().add(inputAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 78, 354, 79));
        getContentPane().add(inputNoTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 169, 354, -1));
        getContentPane().add(inputNoIdentitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 205, 354, -1));
        getContentPane().add(inputNamaKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 269, 354, -1));

        btnHitung.setText("Hitung");
        btnHitung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHitungMouseClicked(evt);
            }
        });
        getContentPane().add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 475, -1, -1));
        getContentPane().add(inputNoPolisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 305, 354, -1));
        getContentPane().add(inputTahunKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 341, 354, -1));
        getContentPane().add(inputHari, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 513, 30, -1));

        jSeparator2.setBackground(new java.awt.Color(74, 31, 61));
        jSeparator2.setForeground(new java.awt.Color(74, 31, 61));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 383, 484, 10));

        labelDariTanggal.setForeground(new java.awt.Color(253, 240, 213));
        labelDariTanggal.setText("Dari Tanggal");
        getContentPane().add(labelDariTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        labelSampai.setForeground(new java.awt.Color(253, 240, 213));
        labelSampai.setText("Sampai");
        getContentPane().add(labelSampai, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));

        labelKali.setForeground(new java.awt.Color(253, 240, 213));
        labelKali.setText("x");
        getContentPane().add(labelKali, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 517, -1, -1));

        labelRpSewa.setForeground(new java.awt.Color(253, 240, 213));
        labelRpSewa.setText("Rp");
        getContentPane().add(labelRpSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 517, -1, -1));
        getContentPane().add(inputBiayaSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 513, 271, -1));

        labelRpBiaya.setForeground(new java.awt.Color(253, 240, 213));
        labelRpBiaya.setText("Rp");
        getContentPane().add(labelRpBiaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 553, -1, -1));

        inputBiayaTotal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        inputBiayaTotal.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(inputBiayaTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 549, 327, -1));

        textTanggal.setForeground(new java.awt.Color(253, 240, 213));
        getContentPane().add(textTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 585, 160, 20));

        table_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama  Peminjam", "No Polisi", "Harga", "Tgl Pinjam", "Tgl Kembali", "Lama Pinjam", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_transaksi.setFocusable(false);
        table_transaksi.setIntercellSpacing(new java.awt.Dimension(0, 0));
        table_transaksi.setRowHeight(25);
        table_transaksi.setSelectionBackground(new java.awt.Color(232, 57, 95));
        table_transaksi.setShowVerticalLines(false);
        table_transaksi.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(table_transaksi);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 600, 590));

        btnKembali.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnKembali.setForeground(new java.awt.Color(253, 240, 213));
        btnKembali.setOpaque(false);
        btnKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKembaliMouseClicked(evt);
            }
        });
        btnKembali.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblKembali.setForeground(new java.awt.Color(253, 240, 213));
        lblKembali.setText("          Kembali");
        btnKembali.add(lblKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 107, 30));

        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 629, 107, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/gradientFormTransaksi.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 667));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHitungMouseClicked
        hitungselisih();
    }//GEN-LAST:event_btnHitungMouseClicked

    private void btnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseClicked
        create();
    }//GEN-LAST:event_btnSubmitMouseClicked

    private void btnRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseClicked
        loadTabel();
    }//GEN-LAST:event_btnRefreshMouseClicked

    private void btnKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKembaliMouseClicked
        this.dispose();
        System.out.println("Panggil Form Sewa");
        FormSewa callForm = new FormSewa();
        callForm.setLocationRelativeTo(null);
        callForm.setVisible(true);
    }//GEN-LAST:event_btnKembaliMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTransaksi(nama,alamat,iden,namak,nopol,tahun,biaya).setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JPanel btnKembali;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JTextArea inputAlamat;
    private javax.swing.JTextField inputBiayaSewa;
    private javax.swing.JTextField inputBiayaTotal;
    private javax.swing.JTextField inputHari;
    private javax.swing.JTextField inputNamaKendaraan;
    private javax.swing.JTextField inputNamaPelanggan;
    private javax.swing.JTextField inputNoIdentitas;
    private javax.swing.JTextField inputNoPolisi;
    private javax.swing.JTextField inputNoSewa;
    private javax.swing.JTextField inputNoTelp;
    private javax.swing.JTextField inputTahunKendaraan;
    private com.toedter.calendar.JDateChooser inputTanggalAkhir;
    private com.toedter.calendar.JDateChooser inputTanggalMulai;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelBiayaSewa;
    private javax.swing.JLabel labelDariTanggal;
    private javax.swing.JLabel labelKali;
    private javax.swing.JLabel labelLamaSewa;
    private javax.swing.JLabel labelNamaKendaraan;
    private javax.swing.JLabel labelNamaPelanggan;
    private javax.swing.JLabel labelNoIdentitas;
    private javax.swing.JLabel labelNoPolisi;
    private javax.swing.JLabel labelNoSewa;
    private javax.swing.JLabel labelNoTelp;
    private javax.swing.JLabel labelRpBiaya;
    private javax.swing.JLabel labelRpSewa;
    private javax.swing.JLabel labelSampai;
    private javax.swing.JLabel labelTahunKendaraan;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblIden;
    private javax.swing.JLabel lblKembali;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNamak;
    private javax.swing.JLabel lblNoSewa;
    private javax.swing.JLabel lblNopol;
    private javax.swing.JLabel lblTahun;
    private javax.swing.JLabel lblTlp;
    private javax.swing.JTable table_transaksi;
    private javax.swing.JLabel textTanggal;
    // End of variables declaration//GEN-END:variables

    public void hitungselisih(){
        try {
            SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
            String strDate1 = df.format(inputTanggalMulai.getDate());
            String strDate2 = df.format(inputTanggalAkhir.getDate());
            Date Tanggal1 = df.parse(strDate1);
            Date Tanggal2 = df.parse(strDate2);
            long Hari1 = Tanggal1.getTime();
            long Hari2 = Tanggal2.getTime();
            long diff = Hari2 - Hari1;
            long Lama = diff / (24 * 60 * 60 * 1000);
            String Hasil = (Long.toString(Lama));
            inputHari.setText(Hasil);
           
            int harga_sewa = Integer.parseInt(lblHarga.getText());
            int lama_sewa = Integer.parseInt(inputHari.getText());
            int Total = harga_sewa * lama_sewa;
            String a = Integer.toString(Total);
            inputBiayaTotal.setText(a);
            
        } catch (Exception a) {
            JOptionPane.showMessageDialog(this, "Masukan Tanggal Peminjaman dan Tanggal Pengembalian");
        }
    }
    
    private void loadTabel(){
        String namaKolom[] = {"id_transaksi", "peminjam", "nopol", "harga", "tgl_pinjaman", "tgl_kembali", "lama", "total"};
        rs = con.querySelect(namaKolom, "transaksi");
        table_transaksi.setModel(new ResultSetTable(rs));
    }
    
    private void clearTabel() {
        inputBiayaTotal.setText("");
        inputHari.setText("");
    }
    
    public void cekstatus() throws SQLException {
        rs = con.querySelectAll("kendaraan", "no_polisi ='" + lblNopol.getText() + "'");
        while (rs.next()) {
            status1 = rs.getString("status");
        }
        String update_status = "Keluar";
        String kolom[] = {"status"};
        String isi[] = {update_status};
        con.queryUpdate("kendaraan", kolom, isi, "no_polisi='" + lblNopol.getText() + "'");
    }

    public boolean jikakeluar() throws SQLException {
        boolean hasil;

        rs = con.querySelectAll("kendaraan", "no_polisi ='" + lblNopol.getText() + "'");
        while (rs.next()) {
            status1 = rs.getString("status");
        }
        if (status1.equals("Keluar")) {
            hasil = false;
        } else {
            hasil = true;
        }
        return hasil;
    }
    
    private void create() {
        try {
            if (!lblNama.getText().isEmpty() && !inputHari.getText().isEmpty()) {
                if (!jikakeluar()) {
                    JOptionPane.showMessageDialog(this, "Maaf motor ini sedang tidak tersedia");
                } else {
                    String kolom[] = {"peminjam", "nopol", "harga", "tgl_pinjaman", "tgl_kembali", "lama", "total"};
                    java.util.Date tgl = (java.util.Date) this.inputTanggalMulai.getDate();
                    java.util.Date tgl1 = (java.util.Date) this.inputTanggalAkhir.getDate();

                    String isi[] = {lblNama.getText(), lblNopol.getText(), lblHarga.getText(), new java.sql.Date(tgl.getTime()).toString(), new java.sql.Date(tgl1.getTime()).toString(), inputHari.getText(), inputBiayaTotal.getText()};
                    System.out.println(con.queryInsert("transaksi", kolom, isi));

                    JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
                    cekstatus();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Data isian ada yang kosong");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error input data");
            System.out.println("salah");
        }
        loadTabel();
        clearTabel();
    }
}

