/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Database.KoneksiDatabase;
import Database.ResultSetTable;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Be
 */
public class FormPelanggan extends javax.swing.JFrame {

    ResultSet rs;
    KoneksiDatabase con;
    
    /**
     * Creates new form FormPelanggan
     */
    public FormPelanggan() {
        con =new KoneksiDatabase(new Database.Parameter().HOST_DB,new Database.Parameter().USERNAME_DB,new Database.Parameter().PASSWORD_DB);
        initComponents();
        loadTabel();
        
        inputIdPelanggan.setEditable(false);
        inputIdPelanggan.setBackground(Color.LIGHT_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelIdPelanggan = new javax.swing.JLabel();
        inputIdPelanggan = new javax.swing.JTextField();
        labelNamaPelanggan = new javax.swing.JLabel();
        inputNamaPelanggan = new javax.swing.JTextField();
        labelAlamat = new javax.swing.JLabel();
        inputAlamat = new javax.swing.JTextArea();
        labelNoTelp = new javax.swing.JLabel();
        inputNoTelepon = new javax.swing.JTextField();
        labelNoIdentitas = new javax.swing.JLabel();
        inputNoIdentitas = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnRefresh = new javax.swing.JPanel();
        lblRefresh = new javax.swing.JLabel();
        btnHapus = new javax.swing.JPanel();
        lblHapus = new javax.swing.JLabel();
        btnUbah = new javax.swing.JPanel();
        lblUbah = new javax.swing.JLabel();
        btnTambah = new javax.swing.JPanel();
        lblTambah = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPelanggan = new javax.swing.JTable();
        btnKembali = new javax.swing.JPanel();
        lblKembali = new javax.swing.JLabel();
        labelCari = new javax.swing.JLabel();
        inputCari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelIdPelanggan.setForeground(new java.awt.Color(253, 240, 213));
        labelIdPelanggan.setText("ID Pelanggan");
        getContentPane().add(labelIdPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 27, -1, -1));
        getContentPane().add(inputIdPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 23, 180, -1));

        labelNamaPelanggan.setForeground(new java.awt.Color(253, 240, 213));
        labelNamaPelanggan.setText("Nama Pelanggan");
        getContentPane().add(labelNamaPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 63, -1, -1));
        getContentPane().add(inputNamaPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 59, 180, -1));

        labelAlamat.setForeground(new java.awt.Color(253, 240, 213));
        labelAlamat.setText("Alamat");
        getContentPane().add(labelAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 94, -1, -1));

        inputAlamat.setColumns(20);
        inputAlamat.setRows(2);
        getContentPane().add(inputAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 100, -1, -1));

        labelNoTelp.setForeground(new java.awt.Color(253, 240, 213));
        labelNoTelp.setText("No. Telepon");
        getContentPane().add(labelNoTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 152, -1, -1));
        getContentPane().add(inputNoTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 148, 177, -1));

        labelNoIdentitas.setForeground(new java.awt.Color(253, 240, 213));
        labelNoIdentitas.setText("No. Identitas");
        getContentPane().add(labelNoIdentitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 184, -1, -1));
        getContentPane().add(inputNoIdentitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 184, 177, -1));

        jSeparator2.setBackground(new java.awt.Color(74, 31, 61));
        jSeparator2.setForeground(new java.awt.Color(74, 31, 61));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 635, 10));

        btnRefresh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnRefresh.setOpaque(false);
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefreshMouseClicked(evt);
            }
        });
        btnRefresh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRefresh.setForeground(new java.awt.Color(253, 240, 213));
        lblRefresh.setText("     Refresh");
        btnRefresh.add(lblRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 78, 30));

        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 224, 76, 30));

        btnHapus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnHapus.setOpaque(false);
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });
        btnHapus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHapus.setForeground(new java.awt.Color(253, 240, 213));
        lblHapus.setText("       Delete");
        btnHapus.add(lblHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 78, 30));

        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 224, 76, 30));

        btnUbah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnUbah.setOpaque(false);
        btnUbah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUbahMouseClicked(evt);
            }
        });
        btnUbah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUbah.setForeground(new java.awt.Color(253, 240, 213));
        lblUbah.setText("         Edit");
        btnUbah.add(lblUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 78, 30));

        getContentPane().add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 224, 76, 30));

        btnTambah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnTambah.setForeground(new java.awt.Color(253, 240, 213));
        btnTambah.setOpaque(false);
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });
        btnTambah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTambah.setForeground(new java.awt.Color(253, 240, 213));
        lblTambah.setText("       Create");
        btnTambah.add(lblTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 224, 76, 30));

        tblPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nama Pelanggan", "Alamat", "No. Telepon", "No. Identitas"
            }
        ));
        tblPelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblPelanggan.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblPelanggan.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tblPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPelangganMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPelanggan);
        if (tblPelanggan.getColumnModel().getColumnCount() > 0) {
            tblPelanggan.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 623, 163));

        btnKembali.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnKembali.setForeground(new java.awt.Color(253, 240, 213));
        btnKembali.setOpaque(false);
        btnKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKembaliMouseClicked(evt);
            }
        });
        btnKembali.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblKembali.setForeground(new java.awt.Color(253, 240, 213));
        lblKembali.setText("          Kembali");
        btnKembali.add(lblKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 107, 30));

        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, 107, 30));

        labelCari.setForeground(new java.awt.Color(253, 240, 213));
        labelCari.setText("Search");
        getContentPane().add(labelCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 270, -1, -1));

        inputCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputCariKeyReleased(evt);
            }
        });
        getContentPane().add(inputCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 270, 323, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconPelanggan.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 130, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/gradientFormPelanggan.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 635, 544));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPelangganMouseClicked
        inputIdPelanggan.setText(String.valueOf(tblPelanggan.getValueAt(tblPelanggan.getSelectedRow(), 0)));
        inputNamaPelanggan.setText(String.valueOf(tblPelanggan.getValueAt(tblPelanggan.getSelectedRow(), 1)));
        inputAlamat.setText(String.valueOf(tblPelanggan.getValueAt(tblPelanggan.getSelectedRow(), 2)));
        inputNoTelepon.setText(String.valueOf(tblPelanggan.getValueAt(tblPelanggan.getSelectedRow(), 3)));
        inputNoIdentitas.setText(String.valueOf(tblPelanggan.getValueAt(tblPelanggan.getSelectedRow(), 4)));
    }//GEN-LAST:event_tblPelangganMouseClicked

    private void btnRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseClicked
        loadTabel();
    }//GEN-LAST:event_btnRefreshMouseClicked

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        try{
            String id=String.valueOf(tblPelanggan.getValueAt(tblPelanggan.getSelectedRow(), 0));
            if(JOptionPane.showConfirmDialog(this, "Yakin menghapus data?", "Peringatan", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
                con.queryDelete("pelanggan","id="+id);
            } else {
                return;
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Pilih id terlebih dahulu");
        }
        loadTabel();
        clear();
    }//GEN-LAST:event_btnHapusMouseClicked

    private void btnUbahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahMouseClicked
        try{
            if( !inputIdPelanggan.getText().isEmpty() && !inputNamaPelanggan.getText().isEmpty() && !inputAlamat.getText().isEmpty() && !inputNoTelepon.getText().isEmpty() && !inputNoIdentitas.getText().isEmpty()){
                String kolom[] = {"id","nama_pelanggan","alamat","no_telp","no_identitas"};
                String isi[] = {inputIdPelanggan.getText(),inputNamaPelanggan.getText(),inputAlamat.getText(),inputNoTelepon.getText(),inputNoIdentitas.getText()};

                con.queryUpdate("pelanggan", kolom, isi, "id='"+String.valueOf(tblPelanggan.getValueAt(tblPelanggan.getSelectedRow(),0))+"'");
                JOptionPane.showMessageDialog(this, "Data Berhasil Diedit");
            } else {
                JOptionPane.showMessageDialog(this, "Data isina ada yang kosong");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error edit data");
        }
        loadTabel();
        clear();
    }//GEN-LAST:event_btnUbahMouseClicked

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        create();
    }//GEN-LAST:event_btnTambahMouseClicked

    private void btnKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKembaliMouseClicked
        this.dispose();
        System.out.println("Panggil Form Sewa");
        FormSewa callForm = new FormSewa();
        callForm.setLocationRelativeTo(null);
        callForm.setVisible(true);
    }//GEN-LAST:event_btnKembaliMouseClicked

    private void inputCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCariKeyReleased
        try {
            rs=con.querySelectAll("pelanggan", "nama_pelanggan LIKE '%"+inputCari.getText()+"%' OR no_telp LIKE '%"+inputCari.getText()+"%'");
            tblPelanggan.setModel(new Database.ResultSetTable(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Pencarian Error");
        }
    }//GEN-LAST:event_inputCariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnHapus;
    private javax.swing.JPanel btnKembali;
    private javax.swing.JPanel btnRefresh;
    private javax.swing.JPanel btnTambah;
    private javax.swing.JPanel btnUbah;
    private javax.swing.JTextArea inputAlamat;
    private javax.swing.JTextField inputCari;
    private javax.swing.JTextField inputIdPelanggan;
    private javax.swing.JTextField inputNamaPelanggan;
    private javax.swing.JTextField inputNoIdentitas;
    private javax.swing.JTextField inputNoTelepon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelCari;
    private javax.swing.JLabel labelIdPelanggan;
    private javax.swing.JLabel labelNamaPelanggan;
    private javax.swing.JLabel labelNoIdentitas;
    private javax.swing.JLabel labelNoTelp;
    private javax.swing.JLabel lblHapus;
    private javax.swing.JLabel lblKembali;
    private javax.swing.JLabel lblRefresh;
    private javax.swing.JLabel lblTambah;
    private javax.swing.JLabel lblUbah;
    private javax.swing.JTable tblPelanggan;
    // End of variables declaration//GEN-END:variables

    private void loadTabel(){
        String namaKolom[] = {"id","nama_pelanggan","alamat","no_telp","no_identitas"};
        rs=con.querySelect(namaKolom, "pelanggan");
        tblPelanggan.setModel(new ResultSetTable(rs));
        }
    
    private void clear(){
        inputIdPelanggan.setText("");
        inputNamaPelanggan.setText("");
        inputAlamat.setText("");
        inputNoTelepon.setText("");
        inputNoIdentitas.setText("");
    }
    
    private void create(){
        try{
            if(!inputNamaPelanggan.getText().isEmpty() && !inputAlamat.getText().isEmpty() && !inputNoTelepon.getText().isEmpty() && !inputNoIdentitas.getText().isEmpty()){
                String kolom[] = {"nama_pelanggan","alamat","no_telp","no_identitas"};
                String isi[] = {inputNamaPelanggan.getText(),inputAlamat.getText(),inputNoTelepon.getText(),inputNoIdentitas.getText()};
                
                System.out.println( con.queryInsert("pelanggan",kolom,isi));
                
                JOptionPane.showMessageDialog(this, "Pelanggan Berhasil ditambahkan");
            } else {
                JOptionPane.showMessageDialog(this, "Data Pelanggan Masih ada yang Kosong");
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error input data");
            System.out.println("salah");
        }
        loadTabel();
        clear();
    }
}
